version: '3.8'

services:
  app:
    build: .
    ports:
      - "50051:50051"
    environment:
      - MONGODB_URI=mongodb+srv://trungnhanforwork:Nhan280803%40@cluster0.qalmkcs.mongodb.net/cmt?retryWrites=true&w=majority&appName=Cluster0&tls=true