# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/face.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/face.proto\x12\x10\x66\x61\x63\x65_recognition\";\n\x0fRegisterRequest\x12\x12\n\nstudent_id\x18\x01 \x01(\t\x12\x14\n\x0cimage_base64\x18\x02 \x01(\t\"4\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\'\n\x0fIdentifyRequest\x12\x14\n\x0cimage_base64\x18\x01 \x01(\t\"\\\n\x10IdentifyResponse\x12\x12\n\nstudent_id\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12\x0f\n\x07message\x18\x04 \x01(\t\"\'\n\x11\x44\x65leteFaceRequest\x12\x12\n\nstudent_id\x18\x01 \x01(\t\"6\n\x12\x44\x65leteFaceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x9e\x02\n\x0f\x46\x61\x63\x65Recognition\x12W\n\x0cRegisterFace\x12!.face_recognition.RegisterRequest\x1a\".face_recognition.RegisterResponse\"\x00\x12W\n\x0cIdentifyFace\x12!.face_recognition.IdentifyRequest\x1a\".face_recognition.IdentifyResponse\"\x00\x12Y\n\nDeleteFace\x12#.face_recognition.DeleteFaceRequest\x1a$.face_recognition.DeleteFaceResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.face_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGISTERREQUEST._serialized_start=38
  _REGISTERREQUEST._serialized_end=97
  _REGISTERRESPONSE._serialized_start=99
  _REGISTERRESPONSE._serialized_end=151
  _IDENTIFYREQUEST._serialized_start=153
  _IDENTIFYREQUEST._serialized_end=192
  _IDENTIFYRESPONSE._serialized_start=194
  _IDENTIFYRESPONSE._serialized_end=286
  _DELETEFACEREQUEST._serialized_start=288
  _DELETEFACEREQUEST._serialized_end=327
  _DELETEFACERESPONSE._serialized_start=329
  _DELETEFACERESPONSE._serialized_end=383
  _FACERECOGNITION._serialized_start=386
  _FACERECOGNITION._serialized_end=672
# @@protoc_insertion_point(module_scope)
