# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import face_pb2 as proto_dot_face__pb2


class FaceRecognitionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterFace = channel.unary_unary(
                '/face_recognition.FaceRecognition/RegisterFace',
                request_serializer=proto_dot_face__pb2.RegisterRequest.SerializeToString,
                response_deserializer=proto_dot_face__pb2.RegisterResponse.FromString,
                )
        self.IdentifyFace = channel.unary_unary(
                '/face_recognition.FaceRecognition/IdentifyFace',
                request_serializer=proto_dot_face__pb2.IdentifyRequest.SerializeToString,
                response_deserializer=proto_dot_face__pb2.IdentifyResponse.FromString,
                )
        self.DeleteFace = channel.unary_unary(
                '/face_recognition.FaceRecognition/DeleteFace',
                request_serializer=proto_dot_face__pb2.DeleteFaceRequest.SerializeToString,
                response_deserializer=proto_dot_face__pb2.DeleteFaceResponse.FromString,
                )


class FaceRecognitionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterFace(self, request, context):
        """Register a face with student ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IdentifyFace(self, request, context):
        """Identify a face and return student ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFace(self, request, context):
        """Delete face embedding by student ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FaceRecognitionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterFace': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterFace,
                    request_deserializer=proto_dot_face__pb2.RegisterRequest.FromString,
                    response_serializer=proto_dot_face__pb2.RegisterResponse.SerializeToString,
            ),
            'IdentifyFace': grpc.unary_unary_rpc_method_handler(
                    servicer.IdentifyFace,
                    request_deserializer=proto_dot_face__pb2.IdentifyRequest.FromString,
                    response_serializer=proto_dot_face__pb2.IdentifyResponse.SerializeToString,
            ),
            'DeleteFace': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFace,
                    request_deserializer=proto_dot_face__pb2.DeleteFaceRequest.FromString,
                    response_serializer=proto_dot_face__pb2.DeleteFaceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'face_recognition.FaceRecognition', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FaceRecognition(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterFace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/face_recognition.FaceRecognition/RegisterFace',
            proto_dot_face__pb2.RegisterRequest.SerializeToString,
            proto_dot_face__pb2.RegisterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def IdentifyFace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/face_recognition.FaceRecognition/IdentifyFace',
            proto_dot_face__pb2.IdentifyRequest.SerializeToString,
            proto_dot_face__pb2.IdentifyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteFace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/face_recognition.FaceRecognition/DeleteFace',
            proto_dot_face__pb2.DeleteFaceRequest.SerializeToString,
            proto_dot_face__pb2.DeleteFaceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
